### ISSUE TITLE
MVP リリース　レビュー依頼 

### ISSUE THREAD

**Issue by miki-ymmt** [miki-ymmt/travel_app#115]
MVP リリース用の issue を作成いたしました。
レビューのほどどうぞよろしくお願いいたします。

## 各種情報
サービス名: Travel Starter
サービスURL: https://travel-starter.onrender.com
GitHub URL: https://github.com/miki-ymmt/travel_app

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [X] ユーザー登録機能、ログイン機能
- [ ] パスワードリセット機能
- [ ] パスポートの取得案内
- [x] パスポート写真登録機能
- [ ] 持ち物リスト機能
- [ ] 持ち物を追加、削除、編集できる機能
- [x] スケジュール作成機能
- [x] 日程や国を選択し、スケジュールを作成できる。
- [x] To Doリスト機能
- [x] スケジュール作成時に選んだ国に応じたTo Doリストを表示する
- [x] チェックボックスで完了したTo Doをチェックできる
- [x] フライト準備サポート機能
- [x] 機内での過ごし方(服装、ストレッチ法、こまめな水分補給の重要性)
- [x] 機内に持ち込みが可能なものと不可能なもののリスト
- [x] 推奨空港到着時間の案内
- [ ] xへのシェア機能
- [ ] お問い合わせフォーム

## READMEレビュー時から変更した機能

**【issue開発レビューとスケジュール面談で本リリースで良いとレビューいただいた機能】**
- パスワードリセット
- お問い合わせフォーム
- xのシェア機能
- パスポートの取得案内（コラム）

**【別機能としてではなく、一つの機能にした機能】**
- 持ち物リスト機能　（TO DOリストと統合）
理由：各持ち物を準備するという意味ではTO DOリストと統合してもユーザーにとっては差し支えないと判断したため。

## サービスイメージがわかるようなスクリーンショット等
| ログイン前トップページ | ログイン後トップページ |
|:----------------------:|:----------------------:|
| ![ログイン前トップページ](https://i.gyazo.com/d906159663bfddde6a30f858d54084f4.jpg) | ![ログイン後トップページ](https://i.gyazo.com/f1ceef2f41e5a92d037deb553054afee.png) |

| 新規登録ページ | ログインページ |
|:----------------------:|:----------------------:|
| ![新規登録ページ](https://i.gyazo.com/c944c898bf2ce2ecbccc01f369ff2867.png) | ![ログインページ](https://i.gyazo.com/3ea920b5ed6c8f774d1f1ed0bc87e5c9.png) |

| 旅登録ページ | 旅詳細ページ |
|:----------------------:|:----------------------:|
| ![旅登録ページ](https://i.gyazo.com/789e1ca8d4cdf0d720f97d5ed2bbbb72.png) | ![旅詳細ページ](https://i.gyazo.com/30c15cd9bfcc93ddcfba69e99b72430e.png) |

| TODOページ | 旅一覧ページ |
|:----------------------:|:----------------------:|
| ![TODOページ](https://i.gyazo.com/d94b3635402e69f12b235ee584ffa8fb.png) | ![旅一覧ページ](https://i.gyazo.com/4690ec8e264d40e17ffe935a4c86d672.png) |

| 旅編集ページ | 旅削除ページ |
|:----------------------:|:----------------------:|
| ![旅編集ページ](https://i.gyazo.com/d7bd0591548b5beaec41c18d5ac45c6e.png) | ![旅削除ページ](https://i.gyazo.com/c576daca3371bbab2c22593251867b3f.png) |

| パスポート情報ページ | フライト情報ページ |
|:----------------------:|:----------------------:|
| ![パスポート情報ページ](https://i.gyazo.com/a78562d1f82be68d7e9427416c4ef0bd.png) | ![フライト情報ページ](https://i.gyazo.com/99de2c6025dcc5c304ec9ef5cf6dc990.png) |

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by miki-ymmt** [comment]
レビューありがとうございました。
引き続きよろしくお願いします。
