### ISSUE TITLE
Jobの実行環境を検討

### ISSUE THREAD

**Issue by miki-ymmt** [miki-ymmt/travel_app#163]
# 概要
RailsのActive Jobとrenderのcron jobを使用して、作成したjob(app/jobs/send_trip_reminder_job.rb)からサービスクラス(app/services/line_notify_service.rb)を呼び出して定期実行をしたい。

renderのcron jobは有料なので、他に方法がないか調査したところ、以下の方法が候補をとしてあがりました。
無料で設定できるようだが、方法として適切なのかを確認したい。

- Google Apps Script
- IFTTT

### 調査したこと(chat GPT)
Google Apps Scriptは、無料で利用できる強力なツールです。以下にGoogle Apps Scriptの利点と考慮点を挙げますので、参考にしてください。

Google Apps Scriptの利点
無料で使用できる:

Google Apps Scriptは無料で利用可能です。特に低頻度のタスク実行には最適です。
簡単なセットアップ:

Google Drive上で簡単にプロジェクトを作成し、スクリプトを書くことができます。設定も直感的で使いやすいです。
強力なスクリプト機能:

Googleの各種サービス（Gmail, Google Sheets, Google Calendarなど）と簡単に連携できるため、複雑なタスクも自動化できます。
豊富なトリガー機能:

時間ベースのトリガーやイベントベースのトリガーを設定できるため、定期的なタスク実行に適しています。
Google Apps Scriptの考慮点
スクリプト実行の制限:

スクリプトの実行時間に制限があります。無料プランでは1日あたりの実行時間が少ないため、非常に高頻度のタスクには向いていないかもしれません。
デバッグとエラーハンドリング:

エラーハンドリングやデバッグのためのツールが限られているため、複雑なスクリプトのトラブルシューティングは難しい場合があります。
セキュリティと認証:

外部APIとの連携には適切な認証処理が必要です。特にプライベートデータを扱う場合には注意が必要です。

### **ゴール**

***
Jobの実行環境を決定する

### **参考記事**
***
[【GAS】GASで定期的にプログラムを実行する](https://zenn.dev/eito_blog/articles/50202178ef91d3)
[Railsガイド　Active Job の基礎](https://railsguides.jp/active_job_basics.html)

### **関連issue**
***
#130 #145 #148 #143 #144 #146

**Comment by Tsuchiya2** [comment]
https://render.com/pricing#cronjobs

> Starter | $0.00016/minute | 512 MB | 0.5


公式ドキュメントを見ると、1分間辺り$0.00016 なので、あまり高額な費用にならないかと思うのですが、期待している処理を実行した場合のおおよその見積もりは算出されたりしましたか？

他の方法でもできるようですが、その手間とcornの費用を天秤にかけた場合、corn以外の方法を模索必要があるか一度考えてみましょう。

**Comment by miki-ymmt** [comment]
土屋さん
ありがとうございます。
計算したところ、1ヶ月で１ドルに満たないであろうという事が予想できたため、元々考えていた実装方法で進めたいと思います。
