### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by miki-ymmt** [miki-ymmt/travel_app#86]
### 実装予定の機能（MVPまで）
- [X] ユーザー登録機能
- [X] ログイン機能
- [X] ログアウト機能
- [X] パスワード変更機能
- [X] パスポートの取得案内と情報登録機能（画像投稿含む）
- [X] 持ち物リスト作成機能
- [X] スケジュール作成機能
- [X] 持ち物リスト編集機能
- [X] 持ち物リスト削除機能
- [X] スケジュール編集機能
- [X] スケジュール削除機能
- [X] TO DOリスト作成機能
- [X] TO DOリスト編集機能
- [X] TO DOリスト削除機能
- [X] フライト準備サポート機能

### 必要なページ
- [X] トップページ
- [X] ホーム画面
- [X] ユーザー登録ページ
- [X] ログインページ
- [X] パスワードリセット申請ページ
- [X] パスワード再設定ページ
- [X] パスポート関連ページ
- [X] パスポート取得案内ページ 
- [X] 旅登録ページ
- [X] 旅詳細ページ
- [X] 旅編集ページ
- [X] TODOページ
- [X] TODO 編集ページ
- [X] 旅一覧ページ　
- [X] フライト関連ページ（モーダル表示）
- [X] 持ち物リストページ
- [X] 持ち物リスト編集ページ
- [X] マイページ
- [X] マイページ編集画面
- [X] お問い合わせページ

**Comment by miki-ymmt** [comment]
GitHub ProjectのURL: https://github.com/users/miki-ymmt/projects/1

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下MVP後の実装で良いかと思ったカードになります。
- マイページ
- お問い合わせ
- パスポート取得ガイド
- i18n
- パスワードリセット
- Mailer
- パスワード再設定

**Comment by miki-ymmt** [comment]
土屋講師

お忙しいところ、レビューいただきありがとうございます。
いただいたアドバイスをもとに、下記のカードを本リリースのTO DOに移動しました。

- マイページ
- お問い合わせ
- パスポート取得ガイド
- i18n
- パスワードリセット
- Mailer
- パスワード再設定
